moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller
    - arm_3dof_controller

  arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: false
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

  gripper_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - gripper_to_jaw1
      - gripper_to_jaw2

  arm_3dof_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true       # varsayılan controller değil
    joints:
      - joint_1
      - joint_2
      - joint_3