joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    auto_repeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 0
      y: 1
      z: 3
    scale_linear:
      x: -1.0
      y: 1.0
      z: 1.0
    scale_linear_turbo:
      x: -15.0
      y: 15.0
      z: 15.0

    # axis_angular:
    #   yaw: 0
    # scale_angular:
    #   yaw: 0.5
    # scale_angular_turbo:
    #   yaw: 1.0
    
    enable_button: 6
    enable_turbo_button: 7

    require_enable_button: true